apiVersion: v1
kind: Service
metadata:
  name: todoapp-svc
  namespace: project-namespace
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 5000
